3 вариант(32,33,34)

Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дано число  𝑅  и массив  𝐴  размера  𝑁 . Найти элемент массива, который наиболее близок к числу  𝑅 .
б) Дана квадратная матрица порядка  𝑀 . Обнулить элементы матрицы, лежащие на побочной диагонали и ниже нее. Условный оператор не использовать.

In [13]:
import numpy as np  # Импортируем библиотеку numpy для работы с массивами

def find_closest_element(R, A):
    A = np.array(A)  # Преобразуем список A в массив numpy для удобства работы
    differences = np.abs(A - R)  # Вычисляем абсолютные значения разности каждого элемента массива A и числа R
    closest_index = np.argmin(differences)  # Находим индекс элемента с минимальной разностью
    return A[closest_index]  # Возвращаем элемент, который ближе всего к числу R

# Тестирование функции
R = 5.5  # Заданное число R
A = [5, 3, 8, 4.5, 6]  # Исходный массив A
closest_element = find_closest_element(R, A)  # Вызываем функцию для нахождения ближайшего элемента
print("Ближайший элемент к числу", R, ":", closest_element)  # Выводим результат


Ближайший элемент к числу 5.5 : 5.0


In [14]:
def zero_matrix_below_secondary_diagonal(M):
    matrix = np.array(M)  # Преобразуем список списков M в матрицу numpy
    n = matrix.shape[0]  # Получаем размерность матрицы (предполагается, что матрица квадратная)
    for i in range(n):  # Перебираем строки матрицы
        for j in range(n - i - 1, n):  # Перебираем столбцы от побочной диагонали до конца строки
            matrix[i, j] = 0  # Обнуляем элементы на побочной диагонали и ниже
    return matrix  # Возвращаем модифицированную матрицу

# Тестирование функции
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])  # Исходная матрица
modified_matrix = zero_matrix_below_secondary_diagonal(M)  # Вызываем функцию для обнуления элементов
print("Модифицированная матрица:")
print(modified_matrix)  # Выводим результат


Модифицированная матрица:
[[1 2 0]
 [4 0 0]
 [0 0 0]]


Задачу решить двумя способами:
Реализовать класс стек через использование списка:
Создать класс Stack с методами:
push(item): добавляет элемент item в верхушку стека;
pop(): удаляет и возвращает элемент из верхушки стека;
peek(): возвращает элемент из верхушки стека без его удаления;
is_empty(): проверяет, пуст ли стек;
size(): возвращает текущий размер стека.
Реализовать класс стек через связный список:
Создать класс Node для представления узла связного списка с двумя атрибутами: data (значение узла) и next (ссылка на следующий узел).
Создать класс Stack с методами:
push(item): добавляет элемент item в верхушку стека;
pop(): удаляет и возвращает элемент из верхушки стека;
peek(): возвращает элемент из верхушки стека без его удаления;
is_empty(): проверяет, пуст ли стек;
size(): возвращает текущий размер стека/
Оба способа реализации должны обеспечивать функциональность стека: добавление элементов в верхушку, удаление элементов из верхушки, получение элемента из верхушки без его удаления, проверку на пустоту и получение текущего размера стека.

Дан стек. Необходимо отсортировать его содержимое по возрастанию или убыванию, в зависимости от переданного параметра (False — по возрастанию, True — по убыванию).

In [15]:
class Stack:
    def __init__(self):
        self.items = []  # Инициализация внутреннего списка


In [16]:
def push(self, item):
    self.items.append(item)  # Добавляет элемент на верх стека

def pop(self):
    return self.items.pop()  # Удаляет и возвращает элемент с верхушки стека

def peek(self):
    if not self.is_empty():
        return self.items[-1]  # Возвращает элемент с верхушки стека без его удаления
    return None  # Возвращает None, если стек пуст

def is_empty(self):
    return len(self.items) == 0  # Проверяет, пуст ли стек

def size(self):
    return len(self.items)  # Возвращает размер стека


In [17]:

### 2. Реализация стека через связный список:

```python
class Node:
    def __init__(self, data):
        self.data = data  # Хранит данные узла
        self.next = None  # Указатель на следующий узел в списке

class Stack:
    def __init__(self):
        self.head = None  # Головной узел стека
        self._size = 0  # Счетчик размера стека

    def push(self, item):
        new_node = Node(item)  # Создает новый узел
        new_node.next = self.head  # Новый узел указывает на предыдущую голову
        self.head = new_node  # Новый узел становится головой
        self._size += 1  # Увеличиваем размер стека

    def pop(self):
        if self.is_empty():
            return None  # Возвращает None, если стек пуст
        popped_node = self.head  # Сохраняем узел, который будет удален
        self.head = self.head.next  # Перемещаем голову на следующий узел
        self._size -= 1  # Уменьшаем размер стека
        return popped_node.data  # Возвращаем данные удаленного узла

    def peek(self):
        if not self.is_empty():
            return self.head.data  # Возвращает данные головного узла
        return None  # Возвращает None, если стек пуст

    def is_empty(self):
        return self.head is None  # Проверяет, пуст ли стек

    def size(self):
        return self._size  # Возвращает текущий размер стека


SyntaxError: invalid syntax (1582398461.py, line 3)

In [18]:
#функция сортировки стека

def sort_stack(stack, descending=False):
    temp_stack = Stack()  # Временный стек для сортировки
    while not stack.is_empty():
        tmp = stack.pop()  # Извлекаем элемент для сравнения
        while not temp_stack.is_empty() and (temp_stack.peek() > tmp if not descending else temp_stack.peek() < tmp):
            stack.push(temp_stack.pop())  # Перемещаем элементы обратно в исходный стек для поддержания порядка
        temp_stack.push(tmp)  # Добавляем элемент в временный стек

    while not temp_stack.is_empty():
        stack.push(temp_stack.pop())  # Перекладываем отсортированные элементы обратно в исходный стек

    if descending:
        reverse_stack(stack)  # Если нужна сортировка по убыванию, переворачиваем стек

def reverse_stack(stack):
    temp_stack = Stack()  # Вспомогательный стек для переворачивания
    while not stack.is_empty():
        temp_stack.push(stack.pop())  # Перекладываем элементы во вспомогательный стек
    while not temp_stack.is_empty():
        stack.push(temp_stack.pop())  # Перекладываем элементы обратно в исходный стек в обратном порядке


Задачу решить двумя способами:
Реализовать класс очередь через использование списка:
Создать класс Queue с методами:
enqueue(item): добавляет элемент item в конец очереди;
dequeue(): удаляет и возвращает элемент из начала очереди;
peek(): возвращает элемент из начала очереди без его удаления;
is_empty(): проверяет, пуста ли очередь;
size(): возвращает текущий размер очереди.
Реализовать класс очередь через связный список:
Создать класс Node для представления узла связного списка с двумя атрибутами: data (значение узла) и next (ссылка на следующий узел).
Создать класс Queue с методами:
enqueue(item): добавляет элемент item в конец очереди;
dequeue(): удаляет и возвращает элемент из начала очереди;
peek(): возвращает элемент из начала очереди без его удаления;
is_empty(): проверяет, пуста ли очередь;
size(): возвращает текущий размер очереди.
Оба способа реализации должны обеспечивать функциональность очереди: добавление элементов в конец, удаление элементов из начала, получение элемента из начала без его удаления, проверку на пустоту и получение текущего размера очереди.

Создать класс очереди с ограниченной емкостью. Если при добавлении элемента очередь уже заполнена, то новый элемент должен заменить первый элемент в очереди.

1. Реализация через использование списка

In [19]:
class Queue:
    def __init__(self):
        self.items = []  # Инициализация пустого списка для элементов очереди

    def enqueue(self, item):
        self.items.append(item)  # Добавляет элемент в конец списка

    def dequeue(self):
        return self.items.pop(0) if not self.is_empty() else None  # Удаляет и возвращает первый элемент списка

    def peek(self):
        return self.items[0] if not self.is_empty() else None  # Возвращает первый элемент списка без удаления

    def is_empty(self):
        return len(self.items) == 0  # Проверяет, пуст ли список

    def size(self):
        return len(self.items)  # Возвращает количество элементов в списке


2. Реализация через связный список

In [20]:
class Node:
    def __init__(self, data=None):
        self.data = data  # Значение узла
        self.next = None  # Ссылка на следующий узел

class Queue:
    def __init__(self):
        self.head = None  # Первый элемент очереди
        self.tail = None  # Последний элемент очереди
        self.count = 0  # Счетчик элементов

    def enqueue(self, item):
        new_node = Node(item)
        if self.is_empty():
            self.head = self.tail = new_node  # Если очередь пуста, новый узел становится и головой, и хвостом
        else:
            self.tail.next = new_node  # Привязываем новый узел к концу очереди
            self.tail = new_node  # Обновляем хвост
        self.count += 1

    def dequeue(self):
        if self.is_empty():
            return None
        removed_data = self.head.data
        self.head = self.head.next  # Перемещаем голову на следующий узел
        if self.head is None:
            self.tail = None  # Если очередь опустела, сбрасываем и хвост
        self.count -= 1
        return removed_data

    def peek(self):
        return self.head.data if not self.is_empty() else None

    def is_empty(self):
        return self.head is None

    def size(self):
        return self.count


3. Класс очереди с ограниченной емкостью

In [21]:
class CircularQueue:
    def __init__(self, capacity):
        self.capacity = capacity  # Максимальная емкость очереди
        self.queue = []
        self.head = 0
        self.tail = -1
        self.size = 0

    def enqueue(self, item):
        if self.size == self.capacity:
            self.dequeue()  # Если очередь полна, удаляем первый элемент
        if self.size < self.capacity:
            if self.tail == self.capacity - 1:
                self.tail = 0  # Циклический сдвиг хвоста
            else:
                self.tail += 1
            if self.size == 0:
                self.head = self.tail  # Если очередь была пуста, голова и хвост совпадают
            self.queue.append(item)
            self.size += 1

    def dequeue(self):
        if not self.is_empty():
            item = self.queue[self.head]
            self.head += 1
            if self.head == self.capacity:
                self.head = 0  # Циклический сдвиг головы
            self.size -= 1
            return item
        return None

    def peek(self):
        return self.queue[self.head] if not self.is_empty() else None

    def is_empty(self):
        return self.size == 0

    def is_full(self):
        return self.size == self.capacity
